GET http://localhost:3000 HTTP/1.1

### get list

GET http://localhost:3000/get_my_user HTTP/1.1

### login
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "Password": "12345678",
    "Email": "admin@gdmail.com"
}
### signup
POST http://localhost:3000/users/signup HTTP/1.1
content-type: application/json

{
    "First_name": "tontanh",
    "Last_name": "kmnv",
    "Password": "12345678",
    "Email": "admin@gdmail.com",
    "Phone":"123456",
    "User_type":"ADMIN"
}
### get list
GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json

### with parammeter
GET http://localhost:3000
    ?page=2

    &pageSize=10

### with token beaer

POST http://localhost:3000
Content-Type: application/json
Authorization: Bearer xxx